name: instagram_clone
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.1
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.1
  flutter_svg: ^2.0.5
  gap: ^3.0.0
  get: ^4.6.5
  image_picker: ^0.8.7+5
  intl: ^0.18.1
  provider: ^6.0.5
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
